homework2: tasks 3, task 4, task 5 completed
dzmitry-prokopchik/freeit pull request #1
Opened 2022-06-19 08:30 UTC by dzmitry-prokopchik

2022-06-19 19:04 UTC, RomanKashenok requested changes

2022-06-19 19:04 UTC, RomanKashenok commented on homework2/src/com/prokopchik/homework2/homeworkTask4.java
> +        System.out.print(x4);
Ты их просто распечатал, а надо бы создать число

2022-06-20 14:59 UTC, i-velichko commented on homework2/src/com/prokopchik/homework2/homeworkTask5.java
> +    /*Дано любое натуральное 4-х значное число. Верно ли, что все цифры числа
Keep docs above the class. It does you main logic more readable.

2022-06-20 14:59 UTC, i-velichko commented on homework2/src/com/prokopchik/homework2/homeworkTask4.java
> +        int n = 1010;
Try to do it with Scanner

2022-06-24 07:41 UTC, closed without merging